=== sunrise30/sandbox-smart-contracts/scripts/assetMetadataSchema.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "object",
    "title": "The Root Schema",
    "required": [
      "name",
      "description",
      "image",
      "animation_url",
      "external_url",
      "properties",
      "sandbox"
    ],
    "properties": {
      "name": {
        "$id": "#/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "default": "",
        "examples": [
          "Helicopter"
        ],
        "pattern": "^(.*)$"
      },
      "description": {
        "$id": "#/properties/description",
        "type": "string",
        "title": "The Description Schema",
        "default": "",
        "examples": [
          "A Speedy Helicopter"
        ],
        "pattern": "^(.*)$"
      },
      "image": {
        "$id": "#/properties/image",
        "type": "string",
        "title": "The Image Schema",
        "default": "",
        "examples": [
          "ipfs://QmRKiVGdNG8wgamGfzRCh9LPzWjwpDJsKSAmw3u6TrDYQe/Helicopter.png"
        ],
        "pattern": "^(.*)$"
      },
      "animation_url": {
        "$id": "#/properties/animation_url",
        "type": "string",
        "title": "The Animation_url Schema",
        "default": "",
        "examples": [
          "ipfs://QmRKiVGdNG8wgamGfzRCh9LPzWjwpDJsKSAmw3u6TrDYQe/Helicopter.gltf"
        ],
        "pattern": "^(.*)$"
      },
      "external_url": {
        "$id": "#/properties/external_url",
        "type": "string",
        "title": "The External_url Schema",
        "default": "",
        "examples": [
          "https://beta.sandbox.game/en/assets/Earth-golem/20802d69-72e3-4e6a-b870-bca94b8134e2/"
        ],
        "pattern": "^(.*)$"
      },
      "properties": {
        "$id": "#/properties/properties",
        "type": "array",
        "title": "The Properties Schema",
        "items": {
          "$id": "#/properties/properties/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "trait_type",
            "display_type",
            "value",
            "max_value"
          ],
          "properties": {
            "trait_type": {
              "$id": "#/properties/properties/items/properties/trait_type",
              "type": "string",
              "title": "The Trait_type Schema",
              "default": "",
              "examples": [
                "power"
              ],
              "pattern": "^(.*)$"
            },
            "display_type": {
              "$id": "#/properties/properties/items/properties/display_type",
              "type": "string",
              "title": "The Display_type Schema",
              "default": "",
              "examples": [
                "ranking"
              ],
              "pattern": "^(.*)$"
            },
            "value": {
              "$id": "#/properties/properties/items/properties/value",
              "type": "integer",
              "title": "The Value Schema",
              "default": 0,
              "examples": [
                30
              ]
            },
            "max_value": {
              "$id": "#/properties/properties/items/properties/max_value",
              "type": "integer",
              "title": "The Max_value Schema",
              "default": 0,
              "examples": [
                100
              ]
            }
          }
        }
      },
      "sandbox": {
        "$id": "#/properties/sandbox",
        "type": "object",
        "title": "The Sandbox Schema",
        "required": [
          "creator",
          "version",
          "classification",
          "voxel_model",
          "creator_profile_url"
        ],
        "properties": {
          "creator": {
            "$id": "#/properties/sandbox/properties/creator",
            "type": "string",
            "title": "The Creator Schema",
            "default": "",
            "examples": [
              "0x61c461EcC993aaDEB7e4b47E96d1B8cC37314B20"
            ],
            "pattern": "^(.*)$"
          },
          "version": {
            "$id": "#/properties/sandbox/properties/version",
            "type": "integer",
            "title": "The Version Schema",
            "default": 0,
            "examples": [
              1
            ]
          },
          "classification": {
            "$id": "#/properties/sandbox/properties/classification",
            "type": "object",
            "title": "The Classification Schema",
            "required": [
              "type",
              "theme",
              "categories"
            ],
            "properties": {
              "type": {
                "$id": "#/properties/sandbox/properties/classification/properties/type",
                "type": "string",
                "title": "The Type Schema",
                "default": "",
                "examples": [
                  "Asset"
                ],
                "pattern": "^(.*)$"
              },
              "theme": {
                "$id": "#/properties/sandbox/properties/classification/properties/theme",
                "type": "string",
                "title": "The Theme Schema",
                "default": "",
                "examples": [
                  "City"
                ],
                "pattern": "^(.*)$"
              },
              "categories": {
                "$id": "#/properties/sandbox/properties/classification/properties/categories",
                "type": "array",
                "title": "The Categories Schema",
                "items": {
                  "$id": "#/properties/sandbox/properties/classification/properties/categories/items",
                  "type": "string",
                  "title": "The Items Schema",
                  "default": "",
                  "examples": [
                    "Vehicle"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            }
          },
          "voxel_model": {
            "$id": "#/properties/sandbox/properties/voxel_model",
            "type": "string",
            "title": "The Voxel_model Schema",
            "default": "",
            "examples": [
              "ipfs://QmRKiVGdNG8wgamGfzRCh9LPzWjwpDJsKSAmw3u6TrDYQe/Helicopter.vxr"
            ],
            "pattern": "^(.*)$"
          },
          "creator_profile_url": {
            "$id": "#/properties/sandbox/properties/creator_profile_url",
            "type": "string",
            "title": "The Creator_profile_url Schema",
            "default": "",
            "examples": [
              "https://beta.sandbox.game/creator/12344"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    }
  }

=== sunrise30/sandbox-smart-contracts/scripts/batch/0.json
{
    "name": "Helicopter",
    "description": "A Speedy Helicopter",
    "image": "ipfs://QmRKiVGdNG8wgamGfzRCh9LPzWjwpDJsKSAmw3u6TrDYQe/Helicopter.png",
    "animation_url": "ipfs://QmRKiVGdNG8wgamGfzRCh9LPzWjwpDJsKSAmw3u6TrDYQe/Helicopter.gltf",
    "external_url": "https://beta.sandbox.game/en/assets/Earth-golem/20802d69-72e3-4e6a-b870-bca94b8134e2/",
    "properties": [
        {
            "trait_type": "power",
            "display_type": "ranking",
            "value": 30, 
            "max_value": 100
        },
        {
            "trait_type": "defense",
            "display_type": "ranking",
            "value": 40, 
            "max_value": 100
        },
        {
            "trait_type": "magic",
            "display_type": "ranking",
            "value": 0, 
            "max_value": 100
        },
        {
            "trait_type": "speed",
            "display_type": "ranking",
            "value": 75, 
            "max_value": 100
        },
        {
            "trait_type": "luck",
            "display_type": "ranking",
            "value": 5, 
            "max_value": 100
        }
    ],
    "sandbox": {
        "creator": "0x61c461EcC993aaDEB7e4b47E96d1B8cC37314B20",
        "version": 1,
        "classification": {
            "type": "Asset",
            "theme": "City",
            "categories": ["Vehicle"]
        },
        "voxel_model": "ipfs://QmRKiVGdNG8wgamGfzRCh9LPzWjwpDJsKSAmw3u6TrDYQe/Helicopter.vxr",
        "creator_profile_url": "https://beta.sandbox.game/creator/12344"
    }
}

=== sunrise30/sandbox-smart-contracts/scripts/batch/3.json
{
    "name": "Spaceship",
    "description": "a spaceship",
    "image": "ipfs://QmXswSjVTjL1pZ7KVuvBnPf7EZ2j6WjHjtEsEY6Kv3jc8U/Spaceship.png",
    "animation_url": "ipfs://QmXswSjVTjL1pZ7KVuvBnPf7EZ2j6WjHjtEsEY6Kv3jc8U/Spaceship.gltf",
    "external_url": "https://beta.sandbox.game/en/assets/Earth-golem/20802d69-72e3-4e6a-b870-bca94b8134e2/",
    "properties": [
        {
            "trait_type": "power",
            "display_type": "ranking",
            "value": 30, 
            "max_value": 100
        },
        {
            "trait_type": "defense",
            "display_type": "ranking",
            "value": 10, 
            "max_value": 100
        },
        {
            "trait_type": "magic",
            "display_type": "ranking",
            "value": 0, 
            "max_value": 100
        },
        {
            "trait_type": "speed",
            "display_type": "ranking",
            "value": 10, 
            "max_value": 100
        },
        {
            "trait_type": "luck",
            "display_type": "ranking",
            "value": 0, 
            "max_value": 100
        }
    ],
    "sandbox": {
        "creator": "0x61c461EcC993aaDEB7e4b47E96d1B8cC37314B20",
        "version": 1,
        "classification": {
            "type": "Asset",
            "theme": "Sci-Fi",
            "categories": ["Vehicle"] 
        },
        "voxel_model": "ipfs://QmXswSjVTjL1pZ7KVuvBnPf7EZ2j6WjHjtEsEY6Kv3jc8U/Spaceship.vxr",
        "creator_profile_url": "https://beta.sandbox.game/creator/12344"
    }
}

=== sunrise30/sandbox-smart-contracts/scripts/batch/2.json
{
    "name": "Magic Stones",
    "description": "Some Magical Stones",
    "image": "ipfs://QmRapnVPhqjS7BRhkjAAfwwRVbrjFFdKAQYFi9y15MNWsS/MagicStones.png",
    "animation_url": "ipfs://QmRapnVPhqjS7BRhkjAAfwwRVbrjFFdKAQYFi9y15MNWsS/MagicStones.gltf",
    "external_url": "https://beta.sandbox.game/en/assets/Earth-golem/20802d69-72e3-4e6a-b870-bca94b8134e2/",
    "properties": [
        {
            "trait_type": "power",
            "display_type": "ranking",
            "value": 20, 
            "max_value": 100
        },
        {
            "trait_type": "defense",
            "display_type": "ranking",
            "value": 0, 
            "max_value": 100
        },
        {
            "trait_type": "magic",
            "display_type": "ranking",
            "value": 50, 
            "max_value": 100
        },
        {
            "trait_type": "speed",
            "display_type": "ranking",
            "value": 0, 
            "max_value": 100
        },
        {
            "trait_type": "luck",
            "display_type": "ranking",
            "value": 30, 
            "max_value": 100
        }
    ],
    "sandbox": {
        "creator": "0x61c461EcC993aaDEB7e4b47E96d1B8cC37314B20",
        "version": 1,
        "classification": {
            "type": "Asset",
            "theme": "Magic",
            "categories": ["Decoration", "Tool"] 
        },
        "voxel_model": "ipfs://QmRapnVPhqjS7BRhkjAAfwwRVbrjFFdKAQYFi9y15MNWsS/MagicStones.vxr",
        "creator_profile_url": "https://beta.sandbox.game/creator/12344"
    }
}
